steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/deck-builder-1b711/deckbox-preview', '.']
    # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/deck-builder-1b711/deckbox-preview']
    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'deckbox-preview', '--image', 'gcr.io/deck-builder-1b711/deckbox-preview', '--region', 'us-central1','--platform', 'managed', '--quiet']
images:
  - gcr.io/deck-builder-1b711/deckbox-preview